// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDpcXguDiCG5hQoJQTCemWUsfR3Rsfm28',
    appId: '1:668645459615:web:0427b24465bbfc9239c4aa',
    messagingSenderId: '668645459615',
    projectId: 'nutriai-edd68',
    authDomain: 'nutriai-edd68.firebaseapp.com',
    storageBucket: 'nutriai-edd68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Hse_d13hoMBMi9swFm8cR6rGEFTJg-Q',
    appId: '1:668645459615:android:f097a825e7cd0f4c39c4aa',
    messagingSenderId: '668645459615',
    projectId: 'nutriai-edd68',
    storageBucket: 'nutriai-edd68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgjmJES9hzMluoVFpORrJZ1Y1h53IYdl8',
    appId: '1:668645459615:ios:f7de6b3a165dd4d739c4aa',
    messagingSenderId: '668645459615',
    projectId: 'nutriai-edd68',
    storageBucket: 'nutriai-edd68.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgjmJES9hzMluoVFpORrJZ1Y1h53IYdl8',
    appId: '1:668645459615:ios:f7de6b3a165dd4d739c4aa',
    messagingSenderId: '668645459615',
    projectId: 'nutriai-edd68',
    storageBucket: 'nutriai-edd68.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDpcXguDiCG5hQoJQTCemWUsfR3Rsfm28',
    appId: '1:668645459615:web:7b6e53994f1abde239c4aa',
    messagingSenderId: '668645459615',
    projectId: 'nutriai-edd68',
    authDomain: 'nutriai-edd68.firebaseapp.com',
    storageBucket: 'nutriai-edd68.firebasestorage.app',
  );
}
